name: Build all ocamlPackages

on:
  workflow_dispatch:
  pull_request:
    branches:
     - master
  push:
    branches:
     - master

permissions:
  contents: read

jobs:
  build:
    # Since nix isolate the build using ubuntu or any other linux is the same
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - run: |
        packages=(ocamlPackages.carton-git ocamlPackages.carton-lwt ocamlPackages.carton ocamlPackages.git-mirage ocamlPackages.git-paf ocamlPackages.git-unix ocamlPackages.git)
        for p in "${packages[@]}"
        do
          nix build --file build.nix --impure "${p}" || nix log --file build.nix --impure "${p}" || true
        done
